In [1]:
from KmeansPPcenters import KMeanPlusPlus
from Gonzalez_centers import Gonzalez
from sklearn.cluster import KMeans
import numpy as np

Cluster Centers: [[ 0.12187426 -0.44077312]
 [-0.15924135  1.00466517]
 [-0.84451919 -0.65799814]]


In [2]:
#dummy data_set
from sklearn import cluster, datasets, mixture
n_samples=100
noisy_circles = datasets.make_circles(n_samples=n_samples, factor=.5,
                                      noise=.05)
dummy_data= noisy_circles[0]

In [3]:
data= dummy_data
num_clusters= 3
init=data[0]

#Get KPP centers
KPP=KMeanPlusPlus(num_clusters=num_clusters, init=init)
KPP.fit(data)
KPP_centers= KPP.centers
print(KPP_centers)

#Get Gonzalez centers
GC_centers = Gonzalez(data, num_clusters=num_clusters, init=init)
print(GC_centers)


[[ 0.62057444 -0.82059407]
 [-0.31853781  0.88424548]
 [ 0.13608232 -0.46628316]]
[[ 0.62057444 -0.82059407]
 [-0.64981882  0.79899163]
 [-0.61242247 -0.91346031]]


In [4]:
#With Gonzalez intialization
kmeans = KMeans(n_clusters=3, init=GC_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print(centroids)

[[ 0.61643406 -0.19691803]
 [-0.13133937  0.5893807 ]
 [-0.44741678 -0.44524558]]


/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [5]:
#With KMeans++ intialization
kmeans = KMeans(n_clusters=3, init=KPP_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print(centroids)

[[ 0.63192928 -0.18822883]
 [-0.13133937  0.5893807 ]
 [-0.43025504 -0.44586433]]


/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [6]:
#With random intialization
kmeans = KMeans(n_clusters=3, init="random")
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print(centroids)

[[ 0.6437383  -0.04868948]
 [-0.33016742 -0.54084608]
 [-0.26685264  0.54399507]]


In [7]:
syn_data= np.loadtxt('syntheticData/data.txt', delimiter=',',unpack=True)

In [8]:
syn_data.shape

(15, 6005)

In [9]:
data= syn_data
num_clusters= 3
init= syn_data[0]

In [10]:
KPP=KMeanPlusPlus(num_clusters=num_clusters, init=init)
KPP.fit(data)
KPP_centers= KPP.centers
print(KPP_centers)

#Get Gonzalez centers
GC_centers = Gonzalez(data, num_clusters=num_clusters, init=init)
print(GC_centers)

[[-35.33204622 -31.78034621  11.32942624 ...  44.68930191  44.30261029
   44.61988552]
 [-13.15812021  25.07707819  46.95557147 ... -33.76462645 -33.17714493
  -32.69385084]
 [ 18.61001886  37.81796849 -22.93398242 ...  -0.27973215  -1.3269147
   -0.4655225 ]]
[[-35.33204622 -31.78034621  11.32942624 ...  44.68930191  44.30261029
   44.61988552]
 [ 43.18477146  36.49402318 -48.26333705 ... -36.72022076 -33.86628919
  -36.01530927]
 [-30.49021007 -48.86737533  47.3599326  ... -21.70028263 -24.15980211
  -23.7835648 ]]


Gconzalez: [[-16.67149987 -21.04338228  15.05385099 ...  14.92967921  15.1945291
   15.19784828]
 [ 13.81092253  25.06311117 -37.56512971 ... -15.29322522 -14.80818016
  -15.30605868]
 [-19.4438002  -18.54585791  26.51158657 ... -28.94499399 -28.45196687
  -28.9530064 ]]


/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [14]:
#With Gonzalez intialization
kmeans = KMeans(n_clusters=num_clusters, init=GC_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("Gconzalez: {}".format(centroids))

#With KMeans++ intialization
kmeans = KMeans(n_clusters=num_clusters, init=KPP_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("KPP: {}".format(centroids))

#With random intialization
kmeans = KMeans(n_clusters=num_clusters, init="random")
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("Random: {}".format(centroids))

/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')