In [1]:
from KmeansPPcenters import KMeanPlusPlus
from Gonzalez_centers import Gonzalez
from sklearn.cluster import KMeans
import numpy as np

Cluster Centers: [[ 0.53962908  0.05769873]
 [-0.94959632 -0.34510509]
 [ 0.30460311  1.03054234]]


In [2]:
#dummy data_set
from sklearn import cluster, datasets, mixture
n_samples=100
noisy_circles = datasets.make_circles(n_samples=n_samples, factor=.5,
                                      noise=.05)
dummy_data= noisy_circles[0]

In [3]:
data= dummy_data
num_clusters= 3
init=data[0]

#Get KPP centers
KPP=KMeanPlusPlus(num_clusters=num_clusters, init=init)
KPP.fit(data)
KPP_centers= KPP.centers
print(KPP_centers)

#Get Gonzalez centers
GC_centers = Gonzalez(data, num_clusters=num_clusters, init=init)
print(GC_centers)


[[ 0.26360211 -1.00440674]
 [-0.38417673 -0.89337436]
 [ 0.20535637  1.00981106]]
[[ 0.26360211 -1.00440674]
 [-0.43478541  1.00247385]
 [ 0.74625237  0.80611852]]


In [4]:
#With Gonzalez intialization
kmeans = KMeans(n_clusters=3, init=GC_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print(centroids)

[[ 0.04187571 -0.61783233]
 [-0.54183801  0.30717124]
 [ 0.53867743  0.33614517]]


/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [5]:
#With KMeans++ intialization
kmeans = KMeans(n_clusters=3, init=KPP_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print(centroids)

[[ 0.48078334 -0.36004394]
 [-0.58515721 -0.24878158]
 [ 0.06474465  0.62899142]]


/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


In [6]:
#With random intialization
kmeans = KMeans(n_clusters=3, init="random")
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print(centroids)

[[ 0.33442109 -0.50512659]
 [ 0.26706022  0.57926561]
 [-0.63371143 -0.0388177 ]]


In [7]:
syn_data= np.loadtxt('syntheticData/data.txt', delimiter=',',unpack=True)

In [9]:
data= syn_data
num_clusters= 3
init= syn_data[0]

In [10]:
KPP=KMeanPlusPlus(num_clusters=num_clusters, init=init)
KPP.fit(data)
KPP_centers= KPP.centers
print(KPP_centers)

#Get Gonzalez centers
GC_centers = Gonzalez(data, num_clusters=num_clusters, init=init)
print(GC_centers)

[[-35.33204622 -31.78034621  11.32942624 ...  44.68930191  44.30261029
   44.61988552]
 [-37.33360374 -33.33258347  -6.46929194 ...  42.09551074  42.51300888
   42.64019819]
 [ 18.61001886  37.81796849 -22.93398242 ...  -0.27973215  -1.3269147
   -0.4655225 ]]
[[-35.33204622 -31.78034621  11.32942624 ...  44.68930191  44.30261029
   44.61988552]
 [ 43.18477146  36.49402318 -48.26333705 ... -36.72022076 -33.86628919
  -36.01530927]
 [-30.49021007 -48.86737533  47.3599326  ... -21.70028263 -24.15980211
  -23.7835648 ]]


In [11]:
#With Gonzalez intialization
kmeans = KMeans(n_clusters=num_clusters, init=GC_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("Gconzalez: {}".format(centroids))

#With KMeans++ intialization
kmeans = KMeans(n_clusters=num_clusters, init=KPP_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("KPP: {}".format(centroids))

#With random intialization
kmeans = KMeans(n_clusters=num_clusters, init="random")
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("Random: {}".format(centroids))

/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)
/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


Gconzalez: [[-16.67149987 -21.04338228  15.05385099 ...  14.92967921  15.1945291
   15.19784828]
 [ 13.81092253  25.06311117 -37.56512971 ... -15.29322522 -14.80818016
  -15.30605868]
 [-19.4438002  -18.54585791  26.51158657 ... -28.94499399 -28.45196687
  -28.9530064 ]]
KPP: [[-12.5390791  -18.58554205  19.35847958 ...   9.4965129    9.73083315
    9.7093783 ]
 [-27.53709622 -43.57959211  26.08644172 ...  10.19766071   9.64448457
    9.4862374 ]
 [  0.47176772  14.98990685 -14.63302901 ... -27.77076317 -26.84471426
  -27.40111153]]
Random: [[ 29.80050205  25.3306839  -34.74311111 ...  -9.94190445  -9.59060984
  -10.52874914]
 [-22.42968849 -17.13761769  26.83507006 ...   1.5441777    1.64825682
    1.84155632]
 [ -9.84620662 -13.49687704 -21.55525909 ... -33.46389384 -32.12928743
  -33.26331217]]
