In [56]:
from KmeansPPcenters import KMeanPlusPlus
from Gonzalez_centers import Gonzalez
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
from numpy import genfromtxt


In [57]:
dirNam = "realData/Skin/"
proDir = "realDataProcessed/"

#Processing skin
fileName = "Skin_NonSkin.txt"

skin = np.genfromtxt(dirNam + fileName, delimiter='')

np.savetxt(proDir + "skin.csv", skin, delimiter=",",  fmt='%f')

In [64]:
skin_data = genfromtxt('realDataProcessed/skin.csv', delimiter=',')
skin_data=skin_data[:,0:3]

In [66]:
%%time
data= skin_data
num_clusters= 3
init=data[0]

#Get KPP centers
KPP=KMeanPlusPlus(num_clusters=num_clusters, init=init)
KPP.fit(data)
KPP_centers= KPP.centers
print(KPP_centers)

#Get Gonzalez centers
GC_centers = Gonzalez(data, num_clusters=num_clusters, init=init)
print(GC_centers)

[[ 74.  85. 123.]
 [162. 160. 112.]
 [ 80.  83.  34.]]
[[ 74.  85. 123.]
 [255. 255. 255.]
 [  0.   0.   0.]]
CPU times: user 30.5 s, sys: 19.8 ms, total: 30.5 s
Wall time: 30.5 s


In [67]:
%%time
#With Gonzalez intialization
kmeans = KMeans(n_clusters=num_clusters, init=GC_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("Gconzalez: {}".format(centroids))

#With KMeans++ intialization
kmeans = KMeans(n_clusters=num_clusters, init=KPP_centers)
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("KPP: {}".format(centroids))

#With random intialization
kmeans = KMeans(n_clusters=num_clusters, init="random")
# Fitting the input data
kmeans = kmeans.fit(data)

# Centroid values
centroids = kmeans.cluster_centers_
print("Random: {}".format(centroids))

/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


Gconzalez: [[174.54639777 171.00095552 129.76263318]
 [111.10043457 144.37944057 212.02359109]
 [ 51.79284687  56.34437356  36.98455144]]


/home/sharv/Programs/anaconda3/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


KPP: [[110.38778667 143.465208   210.98490335]
 [ 51.59865098  55.97689283  35.67638179]
 [174.51677864 170.97387924 129.7386065 ]]
Random: [[ 51.81531715  56.32050348  36.66807494]
 [174.57645387 171.02865434 129.79719463]
 [110.9059832  144.12531565 211.7424802 ]]
CPU times: user 4.36 s, sys: 80 ms, total: 4.44 s
Wall time: 2.44 s
